### ISSUE TITLE
Big Ass fish in Blacklist still getting sold

### ISSUE THREAD

**Issue by spongeboblul** [SoliaRdi/auto-fishing#102] opened 2019-03-31 00:12 UTC
I prefer fishing at Cuttroath Harbor and added the exception "206503" to the blacklist because I don't want this fish to be sold.
I checked the config file and it seems like everything is fine except it still sells every fish inside my inventory. Any advice?

**Comment by SoliaRdi** [comment] 2019-03-31 07:03
Duplicate of #100

**Closed by SoliaRdi** 2019-03-31 07:03 UTC
