### ISSUE TITLE
Dismantle doesn’t work

### ISSUE THREAD

**Issue by Giraffno** [SoliaRdi/auto-fishing#21] opened 2018-12-18 12:28 UTC
After reaching 118/120 inventory slots it opens the dismantle window but says “the item cannot be dismantled”. Yesterday it worked fine and I don’t have maxed out the filets (1646/10000)

**Comment by SoliaRdi** [comment] 2018-12-18 15:49
Can't reproduce this issue, region?

**Comment by Giraffno** [comment] 2018-12-18 15:50
Eu

**Comment by proxyuser15** [comment] 2018-12-18 17:55
Also in EU and having the same issue today (was working fine yesterday).

**Comment by Giraffno** [comment] 2018-12-18 19:44
I removed all the fishes saved into the file config and added them again and now it’s working. I think if you fish something new and don’t add it/add it but don’t save the settings, the dismantle stops working

**Comment by Ebnzo** [comment] 2018-12-18 20:04
issue confirmed, but not related with config file

**Comment by proxyuser15** [comment] 2018-12-18 20:45
hmm i didnt change anything from earlier to now but its somehow working properly again

**Comment by Ebnzo** [comment] 2018-12-18 20:53
I'm running 2 tera clients, first no errors, but second error on the screen

**Comment by Giraffno** [comment] 2018-12-18 20:53
I only run 1 and bugged again 30 minutes ago

**Comment by SoliaRdi** [comment] 2018-12-18 20:57
Where my bugs? T_T

**Comment by SoliaRdi** [comment] 2018-12-18 20:57
Its updated mod, right?

**Comment by SoliaRdi** [comment] 2018-12-18 21:00
give me your config file

**Comment by Ebnzo** [comment] 2018-12-18 21:05
updated mod 
config:
{
	"items": [
		206404,
		206402,
		206405,
		206407,
		206408,
		206409,
		206410,
		206411,
		206412,
		206413,
		206414,
		206415,
		206416,
		206417,
		206418,
		206419,
		206420,
		206421,
		206422,
		206406
	],
	"recipe": 204100,
	"bait": 206001,
	"delay": 2000
}

**Comment by SoliaRdi** [comment] 2018-12-18 21:50
I have one idea about S_SYSTEM_MESSAGE_LOOT_ITEM, unk2 reads as int32, but contain dbid which in other packets uint64

**Comment by Hydra4269** [comment] 2018-12-18 22:01
I don't know what can it be, but so far the only fix to it is constantly trying to dismantle with "/8 fish test" while activating/desactivating the bait... so probably something related to it? also noticed that the "/8 fish test" command doesn't work with the auto-fishing OFF, so basically you need to have auto-fishing ON to make the auto dismantle ON too

**Comment by SoliaRdi** [comment] 2018-12-18 22:53
Should be fixed

**Closed by SoliaRdi** 2018-12-18 22:53 UTC
