### ISSUE TITLE
2 issues, #1 how to change settings back to dismantling fish on inventory full #2 stuck at npc sell window

### ISSUE THREAD

**Issue by kath19x** [SoliaRdi/auto-fishing#91] opened 2019-03-29 07:34 UTC
Hi,,

I got 2 issues:
#1 how to change settings back to dismantling fish on inventory full instead of selling to npc?
and
#2 stuck at npc sell window, it will put all fish on the sell window of npc in vexatus but wont sell it and get stuck there.  I'm sure that C_STORE_COMMIT  is updated as per tera-log.  All opcodes are updated as well and working in protocol.345891 file for Tera SEA.  Ok now what is the problem here?

***
[14:29:43:76] ->          	 C_STORE_COMMIT    (id 59186)
{
    "gameId": "953971961",
    "npc": 0
}
***

***
S_FISHING_BITE = 29236
S_START_FISHING_MINIGAME = 57576
S_FISHING_CATCH = 61637
S_REQUEST_CONTRACT = 25729
C_RQ_COMMIT_DECOMPOSITION_CONTRACT = 28456
C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION = 39925
S_FISHING_CATCH_FAIL = 26569
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46411
C_START_FISHING_MINIGAME = 58013
C_END_FISHING_MINIGAME = 50168
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 53131

C_STORE_COMMIT = 59186

C_STORE_SELL_ADD_BASKET = 60107
S_STORE_BASKET = 53098
***

**Comment by trev44** [comment] 2019-03-29 07:44
Issue 2. I had the same problem.
Dont do fish reloadconf.
Type it all again and save. This worked for me

**Comment by trev44** [comment] 2019-03-29 07:48
Issue 1. Change back to dismantling, fish filetmode + fish filetmode bank
"10000"

**Comment by SoliaRdi** [comment] 2019-03-29 08:09
Duplicate of #88

**Closed by SoliaRdi** 2019-03-29 08:09 UTC

**Comment by kath19x** [comment] 2019-03-29 08:15
trev44 is this the config you are talking about?
**
{
	"delay": 3000,
	"contdist": 10,
	"blacklist": [],
	"filetmode": "sellfishes",
	"selltonpc": true,
	"recipe": 204103,
	"bait": 206004
}
**
I'll change filetmode: "sellfishes" to "10000"?

**Comment by kath19x** [comment] 2019-03-29 08:16
> 
> Issue 2. I had the same problem. Dont do fish reloadconf. Type it all again and save. This worked for me

I never touched reloadconf. And I already retyped it cause I reinstalled the mod

**Comment by kath19x** [comment] 2019-03-29 08:43
Trev, I don't wana bank it, so I'm not sure why you are suggesting to bank and also disable all  fish fillet related stuff as per your command.  Can you elaborate on both of your replies on those 2 issues?  Thanks!

**Comment by kath19x** [comment] 2019-03-29 08:59
Ok the inventory got full and the mod is trying to dismantle fishes and It popped an error "[16:20:55.504] [command] ERROR: TypeError: Cannot read property 'match' of undefined"  Maybe this is the unresolved issue on #88 .  I will wait for an update but for the mean time I can't still make selltonpc work or it is part of the issue and mod needs to be updated?

**Comment by trev44** [comment] 2019-03-29 09:32
ok issue one was to change to dismantling. regarding that. thats what you type.
i do know that your filetmode needs to say bank and not drop.

regarding the selltonpc issue. i had that last night and i just retyped it all 
fish save
fish reloadconf

if it doesnt work for you you will need to ask SoliaRdi unfortunately. 
i just wanted to say what worked for me luckily. sorry yeah

**Comment by kath19x** [comment] 2019-03-29 11:54
trev44 does it all work to you right now? dismantling, selling to npc, etc.
