### ISSUE TITLE
Can't do fish selltonpc <range>

### ISSUE THREAD

**Issue by chingchongbing123** [SoliaRdi/auto-fishing#134] opened 2019-04-16 00:19 UTC
I'm in NA, I always get the message "Warning no seller npc at acceptable range" even when I'm close to the NPCs help. Thank you!

**Comment by SoliaRdi** [comment] 2019-04-16 10:22
When I checked it last time, everything worked = (
I'll watch at it today

**Comment by SoliaRdi** [comment] 2019-04-16 13:22
Duplicate of #132

**Closed by SoliaRdi** 2019-04-16 13:22 UTC
