### ISSUE TITLE
Error Callback and running hook for S_LOAD_TOPO<3>

### ISSUE THREAD

**Issue by Pinduriberkenye** [SoliaRdi/auto-fishing#208] opened 2019-07-24 07:42 UTC
Getting the following errors since yesterday's Patch 83.

https://imgur.com/3V5szAj

https://imgur.com/sW8NWob

**Comment by SoliaRdi** [comment] 2019-07-24 08:20
Duplicate of #204

**Closed by SoliaRdi** 2019-07-24 08:20 UTC

**Comment by SoliaRdi** [comment] 2019-07-24 08:37
S_LOAD_TOPO from quick load btw
