### ISSUE TITLE
Anti-detection features

### ISSUE THREAD

**Issue by ap0521** [SoliaRdi/auto-fishing#119] opened 2019-04-03 13:40 UTC
Due to recent attempts on EU to stop afk fishing, and with other regions likely to follow soon, would it be possible to add features such as:

Random fish catch times, have the module reel in the fish +/- 2000 of the set time to prevent consistent catch logs.

Instant module stop if player position changes, such as when a player is teleported, this way a recast attempt is not sent if a gm teleports you, and player position should generally never change during normal use of the module.

**Comment by SoliaRdi** [comment] 2019-04-03 13:48
All this already exist, delays config too
Duplicate of #118

**Closed by SoliaRdi** 2019-04-03 13:48 UTC
