### ISSUE TITLE
NA opcodes

### ISSUE THREAD

**Issue by Sephyr** [SoliaRdi/auto-fishing#210] opened 2019-07-24 15:12 UTC
Hi there,

Sorry, too hot to install git to do this proper and I just wanted to get my fisher working, but here are the new opcodes + changed filename for NA.

(..\TeraToolbox\node_modules\tera-data\map) - protocol.353337.map

C_END_FISHING_MINIGAME = 61382
C_MEDAL_STORE_BUY_ADD_BASKET = 57478
C_MEDAL_STORE_COMMIT = 51720
C_PUT_WARE_ITEM = 42110
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 44077
C_START_FISHING_MINIGAME = 48769
C_STORE_COMMIT = 31801
C_STORE_SELL_ADD_BASKET = 59642
S_FISHING_BITE = 21035
S_FISHING_CATCH = 37928
S_MEDAL_STORE_BASKET = 50795
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 58645
S_START_FISHING_MINIGAME = 49691
S_STORE_BASKET = 59976

Great mod! Thx!

**Comment by SoliaRdi** [comment] 2019-07-24 15:26
thx
Duplicate of #204

**Closed by SoliaRdi** 2019-07-24 15:26 UTC
