### ISSUE TITLE
inventory fills up and wont go to sellscroll

### ISSUE THREAD

**Issue by tsunpot** [SoliaRdi/auto-fishing#200] opened 2019-07-20 22:26 UTC
fishing acts like normal but wont stop at the usual 3 open inventory spaces. it goes until 2 spaces left and wont fish anymore. I have the sellscroll command active but wont open either npc scroll. NA

**Comment by SoliaRdi** [comment] 2019-07-20 22:38
should be fixed. Issue was caused by caali inven update

**Closed by SoliaRdi** 2019-07-20 22:38 UTC

**Comment by tsunpot** [comment] 2019-07-20 23:37
ok its opening the merchant and gets to selling menu, but now it wont list any fish. when I manually click on fish to add them, it sells when it reaches 8 but then I need to keep adding fish to the sell list

**Comment by SoliaRdi** [comment] 2019-07-20 23:40
try now, updated few minutes ago. Caali messed up slots property before actual patch too
